
import { FaGuitar, FaDrum, FaChalkboardTeacher, FaTools, FaLightbulb, FaWrench, FaHammer, FaCode, FaCamera, FaMusic, FaDumbbell, FaBalanceScale, FaUserMd, FaStethoscope, FaDog, FaBrain, FaPaintBrush, FaFilm, FaPenFancy, FaTractor, FaLeaf, FaPlane, FaShip, FaTree, FaVideo, FaProjectDiagram, FaBullhorn, FaBicycle } from 'react-icons/fa';
import { GiSewingMachine, GiChemicalDrop, GiBee, GiWateringCan, GiBowlingPin, GiGrandPiano, GiViolin } from 'react-icons/gi';
import { MdFitnessCenter, MdPsychology, MdEngineering, MdEdit } from 'react-icons/md';
import { PiChefHat } from 'react-icons/pi';


export const professionsList = [
  { name: "Guitarrista", icon: <FaGuitar /> },
  { name: "Pianista", icon: <GiGrandPiano /> },
  { name: "Baterista", icon: <FaDrum /> },
  { name: "Violinista", icon: <GiViolin /> },
  { name: "Profesor de Inglés", icon: <FaChalkboardTeacher /> },
  { name: "Profesor de Francés", icon: <FaChalkboardTeacher /> },
  { name: "Profesor de Español", icon: <FaChalkboardTeacher /> },
  { name: "Mecánico Automotriz", icon: <FaWrench /> },
  { name: "Mecánico de Bicicletas", icon: <FaBicycle /> },
  { name: "Electricista", icon: <FaLightbulb /> },
  { name: "Fontanero", icon: <FaTools /> },
  { name: "Carpintero", icon: <FaHammer /> },
  { name: "Desarrollador Web", icon: <FaCode /> },
  { name: "Desarrollador de Software", icon: <FaCode /> },
  { name: "Diseñador Gráfico", icon: <FaPaintBrush /> },
  { name: "Fotógrafo", icon: <FaCamera /> },
  { name: "Editor de Fotos", icon: <MdEdit /> },
  { name: "Productor de Música", icon: <FaMusic /> },
  { name: "DJ", icon: <FaMusic /> },
  { name: "Chef", icon: <PiChefHat /> },
  { name: "Panadero", icon: <PiChefHat /> },
  { name: "Pastelero", icon: <PiChefHat /> },
  // { name: "Barista", icon: <FaCoffee /> },
  // { name: "Bartender", icon: <FaCocktail /> },
  // { name: "Nutricionista", icon: <FaAppleAlt /> },
  { name: "Entrenador Personal", icon: <FaDumbbell /> },
  { name: "Instructor de Yoga", icon: <GiBowlingPin /> },
  { name: "Instructor de Pilates", icon: <MdFitnessCenter /> },
  { name: "Consultor de Negocios", icon: <FaBalanceScale /> },
  // { name: "Asesor Financiero", icon: <FaMoneyBillWave /> },
  //{ name: "Contador Público", icon: <FaCalculator /> },
 // { name: "Abogado", icon: <FaGavel /> },
  { name: "Médico General", icon: <FaUserMd /> },
  { name: "Enfermero", icon: <FaStethoscope /> },
  { name: "Fisioterapeuta", icon: <MdPsychology /> },
  { name: "Veterinario", icon: <FaDog /> },
  { name: "Ingeniero Civil", icon: <MdEngineering /> },
  { name: "Ingeniero Eléctrico", icon: <MdEngineering /> },
  { name: "Ingeniero Mecánico", icon: <MdEngineering /> },
 // { name: "Analista de Datos", icon: <FaDatabase /> },
 // { name: "Científico de Datos", icon: <FaMicroscope /> },
 // { name: "Especialista en Ciberseguridad", icon: <FaLock /> },
  { name: "Redactor de Contenidos", icon: <FaPenFancy /> },
  { name: "Copywriter", icon: <FaPenFancy /> },
 // { name: "Traductor", icon: <FaLanguage /> },
  //{ name: "Intérprete", icon: <FaLanguage /> },
  { name: "Coach de Vida", icon: <FaBrain /> },
  //{ name: "Coach de Carreras", icon: <FaRunning /> },
  { name: "Terapeuta", icon: <FaBrain /> },
  { name: "Psicólogo", icon: <MdPsychology /> },
  { name: "Ilustrador", icon: <FaPaintBrush /> },
  { name: "Animador 3D", icon: <FaFilm /> },
  { name: "Diseñador de Moda", icon: <GiSewingMachine /> },
  { name: "Maquillador", icon: <FaPaintBrush /> },
  //{ name: "Estilista de Cabello", icon: <FaCut /> },
  { name: "Instructor de Baile", icon: <FaMusic /> },
  //{ name: "Actor", icon: <FaTheaterMasks /> },
  { name: "Director de Cine", icon: <FaFilm /> },
  { name: "Guionista", icon: <FaPenFancy /> },
 // { name: "Arquitecto", icon: <FaDraftingCompass /> },
  { name: "Agricultor Orgánico", icon: <FaTractor /> },
  { name: "Apicultor", icon: <GiBee /> },
  { name: "Consultor de Energías Renovables", icon: <GiChemicalDrop /> },
  { name: "Piloto de Avión", icon: <FaPlane /> },
 // { name: "Controlador Aéreo", icon: <FaTachometerAlt /> },
 // { name: "Navegante", icon: <FaCompass /> },
  { name: "Marinero", icon: <FaShip /> },
  { name: "Ingeniero Naval", icon: <FaShip /> },
  { name: "Jardinero", icon: <FaTree /> },
  { name: "Paisajista", icon: <GiWateringCan /> },
  { name: "Editor de Video", icon: <FaVideo /> },
  { name: "Gestor de Proyectos", icon: <FaProjectDiagram /> },
  { name: "Especialista en Marketing Digital", icon: <FaBullhorn /> },
 // { name: "Community Manager", icon: <FaUsers /> },
  //{ name: "Especialista en SEO", icon: <FaSearch /> },
];